name = "FreeCell"
uuid = "16865515-0d86-4f18-a7dc-57fa46f959eb"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.1"

[deps]
PlayingCards52 = "c2ceccfa-fa3a-4f0d-8d5f-27465c1854bf"
ImplicitGraphs = "aa20a09e-9376-456a-970d-31341b90bdf0"

[compat]
julia = "1"
PlayingCards52 = "0.0, 0.1, 0.2"
ImplicitGraphs = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
